[
    {
        "key": "Ghadi Detetgent 500gm-22-Feb-2025",
        "name": "Ghadi Detetgent 500gm",
        "batch": "22-Feb-2025",
        "price": 36,
        "quantity": 2,
        "discount": 0,
        "total": "0.07",
        "category": "Non Food Item",
        "paymentStatus": "paid",
        "saleType": "Bank",
        "comment": "",
        "customerName": "General Customer",
        "location": "Natures",
        "type": "Sale",
        "billNo": "UO/1741256796523",
        "totalBillCost": "492.64"
    },
    {
        "key": "Ghadi Detetgent 500gm-25-Feb-2025",
        "name": "Ghadi Detetgent 500gm",
        "batch": "25-Feb-2025",
        "price": 36,
        "quantity": 2,
        "discount": 0,
        "total": "0.07",
        "category": "Non Food Item",
        "paymentStatus": "paid",
        "saleType": "Bank",
        "comment": "",
        "customerName": "General Customer",
        "location": "Natures",
        "type": "Sale",
        "billNo": "UO/1741256796523",
        "totalBillCost": "492.64"
    },
    {
        "key": "Patta Gobhi-23-Feb-2025",
        "name": "Patta Gobhi",
        "batch": "23-Feb-2025",
        "price": 20,
        "quantity": 2000,
        "discount": 0,
        "total": "40.00",
        "category": "Vegetables (Kg)",
        "paymentStatus": "paid",
        "saleType": "Bank",
        "comment": "",
        "customerName": "General Customer",
        "location": "Natures",
        "type": "Sale",
        "billNo": "UO/1741256796523",
        "totalBillCost": "492.64"
    },
    {
        "key": "Patta Gobhi-1-Mar-2025",
        "name": "Patta Gobhi",
        "batch": "1-Mar-2025",
        "price": 20,
        "quantity": 2000,
        "discount": 0,
        "total": "40.00",
        "category": "Vegetables (Kg)",
        "paymentStatus": "paid",
        "saleType": "Bank",
        "comment": "",
        "customerName": "General Customer",
        "location": "Natures",
        "type": "Sale",
        "billNo": "UO/1741256796523",
        "totalBillCost": "492.64"
    },
    {
        "key": "Paneer-06-Mar-2025",
        "name": "Paneer",
        "batch": "06-Mar-2025",
        "price": 550,
        "quantity": 750,
        "discount": 0,
        "total": "412.50",
        "category": "Food Item",
        "paymentStatus": "paid",
        "saleType": "Bank",
        "comment": "",
        "customerName": "General Customer",
        "location": "Natures",
        "type": "Sale",
        "billNo": "UO/1741256796523",
        "totalBillCost": "492.64"
    }
]