{
    "Nature - UO/1741872356248": [
        {
            "Input Date": "13-Mar-2025 6:55 PM",
            "Key": "SauerKraut-15-Jan-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "15-Jan-2025",
            "Price ": "120",
            "Qty": "100",
            "Discount": "0",
            "Total": "12",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741872356248",
            "totalBillCost": "209",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
        {
            "Input Date": "13-Mar-2025 6:55 PM",
            "Key": "Safed Matra-14-Feb-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "14-Feb-2025",
            "Price ": "70",
            "Qty": "100",
            "Discount": "0",
            "Total": "7",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741872356248",
            "totalBillCost": "209",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
      
    ],
    "Nature - UO/1741872444767": [
        {
            "Input Date": "13-Mar-2025 6:57 PM",
            "Key": "Amla-14-Feb-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "14-Feb-2025",
            "Price ": "70",
            "Qty": "30",
            "Discount": "0",
            "Total": "2.1",
            "category": "Vegetables (Kg)",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741872444767",
            "totalBillCost": "17",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
        {
            "Input Date": "13-Mar-2025 6:57 PM",
            "Key": "Amla-28-Feb-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "28-Feb-2025",
            "Price ": "70",
            "Qty": "10",
            "Discount": "0",
            "Total": "0.7",
            "category": "Vegetables (Kg)",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741872444767",
            "totalBillCost": "17",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
       
    ],
    "Nature - UO/1741873274446": [
        {
            "Input Date": "13-Mar-2025 7:11 PM",
            "Key": "SauerKraut-15-Jan-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "15-Jan-2025",
            "Price ": "120",
            "Qty": "100",
            "Discount": "0",
            "Total": "12",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741873274446",
            "totalBillCost": "19",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
        {
            "Input Date": "13-Mar-2025 7:11 PM",
            "Key": "Safed Matra-14-Feb-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "14-Feb-2025",
            "Price ": "70",
            "Qty": "100",
            "Discount": "0",
            "Total": "7",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741873274446",
            "totalBillCost": "19",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        }
    ],
    "Nature - UO/1741873612212": [
        {
            "Input Date": "13-Mar-2025 7:16 PM",
            "Key": "SauerKraut-15-Jan-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "15-Jan-2025",
            "Price ": "120",
            "Qty": "1000",
            "Discount": "0",
            "Total": "120",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741873612212",
            "totalBillCost": "120",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        }
    ],
    "Nature - UO/1741873804115": [
        {
            "Input Date": "13-Mar-2025 7:20 PM",
            "Key": "SauerKraut-15-Jan-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "15-Jan-2025",
            "Price ": "120",
            "Qty": "100",
            "Discount": "0",
            "Total": "12",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741873804115",
            "totalBillCost": "44",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
        {
            "Input Date": "13-Mar-2025 7:20 PM",
            "Key": "Safed Matra-14-Feb-2025",
            "Name": "Nature",
            "Batch/Date of Manufacture": "14-Feb-2025",
            "Price ": "70",
            "Qty": "100",
            "Discount": "0",
            "Total": "7",
            "category": "Food Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741873804115",
            "totalBillCost": "44",
            "mobile": "9205581666",
            "role": "",
            "Email": "",
            "devType": "Non-NKDDevotee"
        },
      
    ],
   
    "Hridaya Parmatma Prabhuji - UO/1741873904323": [
        {
            "Input Date": "13-Mar-2025 7:21 PM",
            "Key": "Mawa-05-Mar-2025",
            "Name": "Hridaya Parmatma Prabhuji",
            "Batch/Date of Manufacture": "05-Mar-2025",
            "Price ": "500",
            "Qty": "300",
            "Discount": "0",
            "Total": "150",
            "category": "dairy Item",
            "paymentStatus": "paid",
            "saleType": "Bank",
            "comment": "",
            "customerName": "General Customer",
            "location": "Natures",
            "type": "Sale",
            "billNo": "UO/1741873904323",
            "totalBillCost": "150",
            "mobile": "9818067711",
            "role": "Admin",
            "Email": "hridayaparmatmadas.gkg@gmail.com",
            "devType": "NKDDevotee"
        }
    ]
}